# Generated by Django 5.1.6 on 2025-03-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_student_id_alter_teacher_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="branch",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
