# Generated by Django 5.1.6 on 2025-03-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_building_tourstep"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("date", models.DateTimeField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="event_images/"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="tourstep",
            name="building",
        ),
        migrations.DeleteModel(
            name="Building",
        ),
        migrations.DeleteModel(
            name="TourStep",
        ),
    ]
